[Patch]

[Setting]
spotify_launch_flags   = 
always_enable_devtools = 0
prefs_path             = /Users/olivertran/Library/Application Support/Spotify/prefs
current_theme          = marketplace
color_scheme           = 
inject_theme_js        = 1
inject_css             = 1
overwrite_assets       = 0
check_spicetify_update = 1
spotify_path           = /Applications/Spotify.app/Contents/Resources
replace_colors         = 1

[Preprocesses]
expose_apis        = 1
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1

[AdditionalOptions]
extensions            = header-font-fix.js
custom_apps           = better-local-files|lastfm-history|lyrics-plus|marketplace|visualizer
sidebar_config        = 0
home_config           = 1
experimental_features = 1

; DO NOT CHANGE!
[Backup]
version = 1.2.90.451.gb094aab0
with    = 2.44.0
